### ISSUE TITLE
Request latest version of Ruby (also some other version, if necessary).

### ISSUE THREAD

**Issue by indrakaw** [scoopinstaller/versions#103]
Reff: https://github.com/lukesampson/scoop/issues/2935

Main Bucket contains Recommended Ruby version of Ruby Installer: 2.5. It would nice to have different versions of Ruby. The latest and older ones.

An exclusive Scoop Bucket for Ruby, as Java and PHP done, is a good idea.

**Comment by r15ch13** [comment]
Added `ruby24` and `ruby25` with https://github.com/scoopinstaller/versions/commit/2e0c06f36cd5857ab8e5d49ca0449e5b08f6bda1
