### ISSUE TITLE
[Request]: Add godot3 and godot3-mono

### ISSUE THREAD

**Issue by Calinou** [ScoopInstaller/Versions#1060]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] English interface (or at least English documentation)
- [X] Alternative, forked or prerelease version of an existing package
- [X] Fairly standard install (e.g. no elaborate pre/post install scripts)

### Name

Godot

### Description

Cross-platform game engine

### Homepage

https://godotengine.org

### Download Link(s)

https://godotengine.org/download

### Corresponding package

godot4, godot4-mono

### Some Indication of Popularity/Repute

Many users are still relying upon Godot 3 (and we expect this to continue for at least a year), so we should have a way to install Godot 3 using Scoop.

`godot4` and `godot4-mono` can be removed since they've been replaced by godot and godot-mono in the `extras` bucket.

**Comment by digitalbricklayer** [comment]
Godot 4 is not the currently the long term support version version of Godot 3.5. Being able to install either Godot 3.5 or Godot 4 would be ideal.
