### ISSUE TITLE
[Request]: llvm-mingw

### ISSUE THREAD

**Issue by ghost** [ScoopInstaller/Versions#1290]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] English interface (or at least English documentation)
- [X] Alternative, forked or prerelease version of an existing package
- [X] Fairly standard install (e.g. no elaborate pre/post install scripts)

### Name

llvm-mingw

### Description

Another LLVM/LLD-based MinGW distro

### Homepage

https://github.com/mstorsjo/llvm-mingw

### Download Link(s)

https://github.com/mstorsjo/llvm-mingw/releases

### Corresponding package

versions/mingw-winlibs-llvm and versions/mingw-winlibs-llvm-ucrt

### Some Indication of Popularity/Repute

It actually has twice as many stars as the mingw-winlibs-llvm that's currently packaged, and unlike that one is actually packaged correctly so that nontrivial projects actually build (eg [llama.cpp](https://github.com/ggerganov/llama.cpp), [libjxl](https://github.com/libjxl/libjxl) as far as I've tested). It probably also warrants being split into msvcrt and urct versions like its brother.

**Comment by chawyehsu** [comment]
Available in the Main bucket with the name `mingw-mstorsjo-llvm-ucrt`
