### ISSUE TITLE
neovim-nightly@0.10.0-dev-1055-gb7734c4ec: hash check failed

### ISSUE THREAD

**Issue by mkhennoussi** [ScoopInstaller/Versions#1391]
Checking hash of nvim-win64.zip ... ERROR Hash check failed!
App:         versions/neovim-nightly
URL:         https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    6388af6c6c5d63e77d5c29aa470263509ed201d36d3736411f80671fdb61067d
Actual:      a62f63f41878b768f93bc71442416c5db64b773020aca9f694e45f4c77ca5c1b

**Comment by jeeeem** [comment]
@mkhennoussi I believe there is a bug right now in updating nighty version of neovim, maybe its scoop issue cos this version was the latest version when I reported it. See this. https://github.com/ScoopInstaller/Versions/issues/1387
