### ISSUE TITLE
[Bug]: Cannot install `python312` (the same way as `python311`, `python310`, ...)

### ISSUE THREAD

**Issue by bersbersbers** [ScoopInstaller/Versions#1422]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

python

### Expected/Current Behaviour

For CI (matrix) testing, it would be useful to be able to install different Python version using essentially the same command. For example, v3.10 and v3.11 can be installed using `scoop install python310` and `scoop install python311`, respectively. However, v3.12 can*not* be installed using `scoop install python312`. I think `python312` should be added before v3.13 comes out.

### Steps to Reproduce

```console
PS> scoop install python312
Couldn't find manifest for 'python312'.
```

### Possible Solution

Add `python312`

### Scoop and Buckets Version

```console
PS> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'main' bucket:
95c009c5b (HEAD -> master, origin/master, origin/HEAD) rclone: Update to version 1.64.2

'versions' bucket:
a4be5da56 (HEAD -> master, origin/master, origin/HEAD) rclone-beta: Update to version 1.65.0-beta.7447.b0a87d7cf
```

### Scoop Config

```console
(irrelevant)
```

### PowerShell Version

```console
(irrelevant)
```

**Comment by jinzhijie** [comment]
Same. looking for `python312` support

**Comment by bersbersbers** [comment]
@jinzhijie unless you are also installing in an automated way, check out `python` from the main bucket.

**Comment by HUMORCE** [comment]
https://github.com/ScoopInstaller/Versions/commit/944e11c8bcba3ef10b0cf4dee7ac031ab9973462

python312 added.
