### ISSUE TITLE
python27@2.7.16: hash check failed

### ISSUE THREAD

**Issue by ntt2k** [ScoopInstaller/Versions#145]
λ scoop install python27
Installing 'python27' (2.7.16) [64bit]
python-2.7.16.amd64.msi (19.4 MB) [===========================================================================================================================] 100%
Checking hash of python-2.7.16.amd64.msi ... ERROR Exception calling ".ctor" with "0" argument(s): "This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms."
ERROR Hash check failed!
App:         versions/python27
URL:         https://www.python.org/ftp/python/2.7.16/python-2.7.16.amd64.msi
First bytes: D0 CF 11 E0 A1 B1 1A E1
Expected:    2fe86194bb4027be75b29852027f1a79
Actual:

**Comment by rasa** [comment]
The hash 2fe86194bb4027be75b29852027f1a79 in the manifest (the “expected” hash above) is correct. Please try again.
