### ISSUE TITLE
neovim-nightly hash error

### ISSUE THREAD

**Issue by kls1991** [ScoopInstaller/Versions#1463]
### Prerequisites

- [X] I have used the predefined issue title. (e.g. "xxx@xxx&#58; hash check failed")
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name and Version

neovim-nightly@0.10.0-4880385

**Comment by kls1991** [comment]
Installing 'neovim-nightly' (0.10.0-4880385) [64bit] from versions bucket
nvim-win64.zip (16.3 MB) [====================================================================] 100%
Checking hash of nvim-win64.zip ... ERROR Hash check failed!
App:         versions/neovim-nightly
URL:         https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    7ae2bcacb95bf28f35490de3f674104ebe19092e17c3d2d7c5892c05385d1a5b
Actual:      67be74a4b7b14af4c50c5d3b803ffdb8b7a4a63dd018e47f830b1d6f6903851b

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Versions/issues/new?title=neovim-nightly%400.10.0-4880385%3a+hash+chec
k+failed

**Comment by HUMORCE** [comment]
cannot reproduce with current verison
