### ISSUE TITLE
neovim-nightly 0.10.0-1746  hash check failed

### ISSUE THREAD

**Issue by cx29** [ScoopInstaller/Versions#1481]
### Prerequisites

- [X] I have used the predefined issue title. (e.g. "xxx@xxx&#58; hash check failed")
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name and Version

neovim-nightly@0.10.0-1746

**Comment by cx29** [comment]
this is my log:

Installing 'neovim-nightly' (0.10.0-1746) [64bit] from versions bucket
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: c3dd1a|OK  |   2.5MiB/s|C:/Users/cx/scoop/cache/neovim-nightly#0.10.0-1746#https_github.com_neovim_neovim_releases_download_nightly_nvim-win64.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of nvim-win64.zip ... ERROR Hash check failed!
App:         versions/neovim-nightly
URL:         https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    b8fbfbd012ab6acc215c839403f1002e2f1d6f522ee7e7ea11891b570e4355f0
Actual:      952f59debd89933c4457d4b55fe36caab35f76b22133a664deeaa6d0382b4249

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Versions/issues/new?title=neovim-nightly%400.10.0-1746%3a+hash+check+failed

![image](https://github.com/ScoopInstaller/Versions/assets/64113027/0f408d80-5939-427a-916f-d9e8a926011f)
![image](https://github.com/ScoopInstaller/Versions/assets/64113027/3c604c20-7c73-43c7-b52b-7a8a3a49991c)

**Comment by HUMORCE** [comment]
cannot reproduce with current version.
