### ISSUE TITLE
[Bug]: Python39 on scoop is on 3.9.13, official release is on 3.9.18

### ISSUE THREAD

**Issue by Ravencentric** [ScoopInstaller/Versions#1509]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

python39

### Expected/Current Behaviour

Current:
`scoop install versions/python39` installs `Python 3.9.13`
Expected:
`scoop install versions/python39` installs `Python 3.9.18`

### Steps to Reproduce

```console
1. Run `scoop install versions/python39`
2. Check the installed version
```

### Possible Solution

Update bucket with 3.9.18

### Scoop and Buckets Version

```console
PS> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
c57864a86 (HEAD -> master, origin/master, origin/HEAD) saber: Update to version 0.18.6

'main' bucket:
003af7e55 (HEAD -> master, origin/master, origin/HEAD) rdiff-backup: Update to version 2.2.5

'nonportable' bucket:
8d658ac (HEAD -> master, origin/master, origin/HEAD) anki-np: Update to version 23.12

'versions' bucket:
89c87b9e8 (HEAD -> master, origin/master, origin/HEAD) vlc-nightly: Update to version 20231225
```

### Scoop Config

```console
PS> scoop config

last_update            scoop_repo                              scoop_branch
-----------            ----------                              ------------
25-12-2023 01:44:28 PM https://github.com/ScoopInstaller/Scoop master
```

### PowerShell Version

```console
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by HUMORCE** [comment]
> security:
only security fixes are accepted and no more binaries are released, but new source-only versions can be released
> 
> https://devguide.python.org/versions/#status-key

PSF does not provides binary installer for security updates versions.

Built from source or use unofficial build instead, Scoop will not switch to unofficial builds.
