### ISSUE TITLE
[Request]: yt-dlp-nightly

### ISSUE THREAD

**Issue by soredake** [ScoopInstaller/Versions#1667]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] English interface (or at least English documentation)
- [X] Alternative, forked or prerelease version of an existing package
- [X] Fairly standard install (e.g. no elaborate pre/post install scripts)

### Name

yt-dlp-nightly

### Description

yt-dlp nightly builds

### Homepage

https://github.com/yt-dlp/yt-dlp

### Download Link(s)

https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/download/2024.03.29.232706/yt-dlp.exe

### Corresponding package

main yt-dlp

### Some Indication of Popularity/Repute

https://github.com/yt-dlp/yt-dlp

**Comment by aaronliu0130** [comment]
Note that there is yt-dlp-daily, the deprecated version that hasn't been updated since 2023-03, in here.
