### ISSUE TITLE
[Request] Handle Python user base scripts directory

### ISSUE THREAD

**Issue by bryanburke** [ScoopInstaller/Versions#196]
The Scoop manifests for Python versions ([python27.json](https://github.com/ScoopInstaller/Versions/blob/4711d74fb2ae4fe756bc400fe55dcb66cc009c33/bucket/python27.json), [python35.json](https://github.com/ScoopInstaller/Versions/blob/8ad4f23c70d1164ee23c0e159157d8353bcf7593/bucket/python35.json), [python36.json](https://github.com/ScoopInstaller/Versions/blob/8ad4f23c70d1164ee23c0e159157d8353bcf7593/bucket/python36.json), and [python37.json](https://github.com/ScoopInstaller/Versions/blob/6cbe65817936b3650b5ac6b9f33ed8add3b7f842/bucket/python37.json)) do not handle the Python [user base](https://docs.python.org/3/library/site.html#site.USER_BASE) scripts directory, so CLI scripts from packages installed in user mode (`pip install --user`) are not available on the PATH. Performing [user installations](https://pip.pypa.io/en/stable/user_guide/#user-installs) of packages is considered best practice, and many packages (such as the popular [Pipenv](https://pipenv.readthedocs.io/en/latest/install/#pragmatic-installation-of-pipenv)) recommend doing them.

Two possible solutions might be:

1. Construct the user base scripts directory and add it to PATH. The path can be constructed as follows: `Join-Path -Path (Split-Path -Path (python -m site --user-site) -Parent) -ChildPath Scripts`
1. Point the [PYTHONUSERBASE](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONUSERBASE) environment variable to a directory within the Python install directory and persist it.

Related issue: ScoopInstaller/Main#772

**Comment by dwettstein** [comment]
Installing Python using Scoop is already done on user-level (without `--global` flag) , so there is no need to additionally install packages using the `--user` flag.

If you still need to install packages on user-level and have them in the `PATH`, I suggest to create a PR. Paths are added to ENV using `env_add_path`.

> env_add_path: Add this directory to the user's path (or system path if --global is used). The directory is relative to the install directory and must be inside the install directory.

https://github.com/ScoopInstaller/Main/blob/e4e85d903e6ff7adfca6d4b49a03bd50835674b9/bucket/python.json#L84
