### ISSUE TITLE
gradle4@4.10.3: download via aria2 failed

### ISSUE THREAD

**Issue by guoyitao** [ScoopInstaller/Versions#213]
Starting download with aria2 ...
Download: [#03fc82 0B/0B CN:1 DL:0B]
Download: [#03fc82 0B/0B CN:1 DL:0B]
Download: [#03fc82 0B/0B CN:1 DL:0B]
Download: 08/09 19:30:02 [ERROR] CUID#8 - Download aborted. URI=https://services.gradle.org/distributions/gradle-4.10.3-all.zip
Download: Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://downloads.gradle-dn.com/distributions/gradle-4.10.3-all.zip
Download:   -> [SocketCore.cc:1021] errorCode=1 SSL/TLS handshake failure: Error: 鎿嶄綔鎴愬姛瀹屾垚銆?
Download: (0)
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 03fc82|ERR |       0B/s|E:/scoopApp/cache/gradle4#4.10.3#https_services.gradle.org_distributions_gradle-4.10.3-all.zip
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.
ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://services.gradle.org/distributions/gradle-4.10.3-all.zip
    referer=https://services.gradle.org/distributions/
    dir=E:\scoopApp\cache
    out=gradle4#4.10.3#https_services.gradle.org_distributions_gradle-4.10.3-all.zip

ERROR & 'E:\scoopApp\apps\aria2\current\aria2c.exe' --input-file='E:\scoopApp\cache\gradle4.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=17924 --continue --all-proxy='127.0.0.1:1080'

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Versions/issues/new?title=gradle4%404.10.3%3a+download+via+aria2+failed

**Comment by HUMORCE** [comment]
please check your network settings.
