### ISSUE TITLE
neovim-nightly update

### ISSUE THREAD

**Issue by farisachugthai** [ScoopInstaller/Versions#233]
Hey so I'm not 100% sure that I understand how the code base works otherwise I'd consider creating a pull request.

Unfortunately, neovim-nightly hasn't updated in a couple months even though the official repo comes out with a new binary every day.

I don't know if this is something that could be checked or automatically updated to change with the daily updates but if that was possible that'd be amazing.

Otherwise I want to thank the maintainers because scoop is genuinely one of the best PowerShell repos I've gotten comfortable using!

**Comment by kirawi** [comment]
You have to reinstall neovim-nightly whenever it updates because the current script lacks a checkver.

**Comment by farisachugthai** [comment]
But I'm saying it hasn't been updating

**Comment by kirawi** [comment]
I mean when neovim releases an update. The script itself can't do version checking.

**Comment by farisachugthai** [comment]
Ohhhhh. Uhm is there simple way that that could be added back?

**Comment by kirawi** [comment]
I don't know, I'm assuming there was a reason for it.

**Comment by farisachugthai** [comment]
At the risk of sounding like a pest, this is the pull request where it was removed.

There's nothing really here to indicate that there was:

https://github.com/ScoopInstaller/Versions/pull/156

@niheaven 

Can I ask why the checkver was removed and if there's anything stopping it from being added back in?

**Comment by niheaven** [comment]
Nightly means you always install latest version, but yes, no checkver. If you really want to update nightly version, please reinstall it (update -f).
