### ISSUE TITLE
App Request : TDM-GCC

### ISSUE THREAD

**Issue by Lunchb0ne** [ScoopInstaller/Versions#237]
Can we have [TDM-GCC](https://jmeubank.github.io/tdm-gcc/about/) in the bucket too?
It's a really good alternative to using vanilla gcc.

**Comment by rashil2000** [comment]
Hey @tech189, would you like to take this one too?

No hurries though, just asking for help in clearing some backlog :)

**Comment by tech189** [comment]
This is certainly a tricky one! I got checkver working, which I hope covers the non-standard versioning they use. As for the installation, it looks like there's a ton of compressed files that get extracted and then their bins which are registered, plus some start menu shortcuts, see the installation log below.

Manifest so far:
```json
{
    "version": "10.3.0",
    "description": "GCC compiler, Windows-friendly",
    "homepage": "https://jmeubank.github.io/tdm-gcc/",
    "license": "CC0-1.0",
    "architecture": {
        "64bit": {
            "url": "https://github.com/jmeubank/tdm-gcc/releases/download/v10.3.0-tdm64-2/tdm64-gcc-10.3.0-2.exe#dl.7z",
            "hash": "819c7a1f74d45ad04e10662e1a2c3124d13d9a2bca508847692251242cd455c3"
        },
        "32bit": {
            "url": "https://github.com/jmeubank/tdm-gcc/releases/download/v10.3.0-tdm-1/tdm-gcc-10.3.0.exe#dl.7z",
            "hash": "f6ed81c0e1cc4199ecf0488446f2396e20a56d731a0c80899afcd41ffb2c0e1c"
        }
    },
    "checkver": {
        "regex": "MinGW-w64 based.+\\s.+download\\/(?<win64>v(?<version>[\\d.]+).+\\/tdm64-gcc-[\\d.-]+.exe)\".+\\s.+\\s.+download\\/(?<win32>v.+\\/tdm-gcc-[\\d.-]+.exe)\""
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/jmeubank/tdm-gcc/releases/download/$matchWin64#dl.7z"
            },
            "32bit": {
                "url": "https://github.com/jmeubank/tdm-gcc/releases/download/$matchWin32#dl.7z"
            }
        }
    }
}

```
Installation log:

https://gist.github.com/tech189/41ce746b3dd541f625b9d89be7a6efd1

**Comment by rashil2000** [comment]
Okay. So in a `pre_install` step, we will have to extract all files in the $PLUGINSDIR directory that end with `.tar.xz` and `.tar.lzma`, into the root directory: 

![image](https://user-images.githubusercontent.com/46838874/147869761-71cc810d-4178-408c-8bae-ab2de3c33b9f.png)

**Comment by rashil2000** [comment]
Example: https://github.com/chawyehsu/dorado/blob/master/bucket/nuwen-mingw-gcc.json

**Comment by rasa** [comment]
See also https://github.com/mapleafgo/scoop-bucket/blob/master/bucket/tdm-gcc.json . I'm not suggesting using this, but just pointing it out for reference.

**Comment by rasa** [comment]
See also https://github.com/rivy/scoop-bucket/blob/master/gcc@9.2.0-multilib.json . Same caveat.

**Comment by tech189** [comment]
Thanks for your help guys, I'm almost there, just trying to recreate a shortcut that the installer does in the last step. It creates a shortcut that has the target of `%comspec% /k ""C:\TDM-GCC-64\mingwvars.bat""` but scoop needs an exe/bat that is located in the installation dir so I can't specify `cmd.exe` in the shortcut like so: 
```json
"shortcuts": [
        [
            "cmd.exe",
            "MinGW Command Prompt",
            "/k \"$dir\\mingwvars.bat\""
        ]
    ],
```
I tried just putting the bat file as the shortcut but for some reason it opens and immediately exits. If I double click the bat file it doesn't open either, it only works when I run `cmd.exe /k "C:\Users\me\scoop\apps\tdm-gcc\current\mingwvars.bat"` from a cmd line. Any ideas?

**Comment by rashil2000** [comment]
What does the bat file contain? I think it only contains a command to add TDM GCC's bin directory to PATH. This is why it immediately exits.

So we might not need it.

**Comment by tech189** [comment]
I think that's exactly what it contains:
```bat
@echo.
@echo Setting up environment for using MinGW with GCC from %~dp0.
@set PATH=%~dp0bin;%PATH%
```

**Comment by rashil2000** [comment]
Yup, we don't need it, since we'll already be having an `env_add_path` in the manifest

**Comment by tech189** [comment]
I submitted the PR. It would be great if @Lunchb0ne or someone else who uses GCC could test the bins and PATH, as I do not work with it myself.

**Comment by Lunchb0ne** [comment]
Yeah, It's perfect, thanks for the hard work @tech189!
