### ISSUE TITLE
python27@2.7.18: decompress error

### ISSUE THREAD

**Issue by gigilsu** [ScoopInstaller/Versions#264]
Failed to extract files from C:\Users\gcarv\scoop\apps\python27\2.7.18\python-2.7.18.amd64.msi.
Log file:
  ~\scoop\apps\python27\2.7.18\msi.log

Note: I was not able to install python via windows installer either. I have 3 installed but need 2 for a project. I am using windows 10

**Comment by HUMORCE** [comment]
try:
```
scoop config MSIEXTRACT_USE_LESSMSI ture
scoop uninstall python27
scoop install python27
```

if problem still, reopen this issue.
