### ISSUE TITLE
[Request] Add android-studio-canary

### ISSUE THREAD

**Issue by Jojo4GH** [ScoopInstaller/Versions#274]
- **URL to application**: <https://developer.android.com/studio/preview> and <https://developer.android.com/studio/archive>
- **Latest version**: 2020.3.1
- **Graphical interface**: Yes
- **Portable version**: Yes (zip) 

The manifest for the stable version already exists here: <https://github.com/lukesampson/scoop-extras/blob/master/bucket/android-studio.json>

**Comment by tech189** [comment]
I had a go, but annoyingly I can't get regex to match a version number, I've got this so far if anyone wants to try:
```
"checkver": {
    "regex": "Download \\w+ \\(([\\d.]+)\\) Canary (\\d+)",
    "replace": "${0}.${1}"
},
```

**Comment by tech189** [comment]
Turns out it's because the site changes the HTML if you visit it with a browser while checkver downloads the original HTML before any changes. Making a PR now.

**Comment by tech189** [comment]
@Jojo4GH it's added now, try installing with `scoop install android-studio-canary`
