### ISSUE TITLE
[Request] Add Tomcat9

### ISSUE THREAD

**Issue by thorstenkampe** [ScoopInstaller/Versions#283]
Tomcat 10 has been published in the `extras` bucket today. Are there any plans to publish Tomcat9 in `versions`?

Would it be possible to persist `conf` and `webapps` (see [Tomcat: conf and webapps directories are not persisted](https://github.com/lukesampson/scoop-extras/issues/6010))?

**Comment by davidxuang** [comment]
Is the `persist` required by all tomcat versions?

**Comment by thorstenkampe** [comment]
@davidxuang , yes the requirement does apply to all Tomcat versions.
