### ISSUE TITLE
[Request] Add VLC Nightly

### ISSUE THREAD

**Issue by sitiom** [ScoopInstaller/Versions#284]
- **URL to application**: https://nightlies.videolan.org/
- **Latest version**: nightly
- **Graphical interface**: Yes
- **Portable version**: Yes

**Comment by tech189** [comment]
We can base it on the manifest in extras: https://github.com/ScoopInstaller/Extras/blob/master/bucket/vlc.json

We can get the version number (date/time stamp of build) with this checkver:
```
"checkver": {
        "url": "https://artifacts.videolan.org/vlc/nightly-win64/",
        "regex": "(\\d+-\\d+)"
    },
```

But the main issue is that each build has a filename that ends with the last commit of the build, e.g. https://artifacts.videolan.org/vlc/nightly-win64/20211125-0422/vlc-4.0.0-dev-win64-16d6b231.7z

I couldn't find a page with both the build number and the commit id that checkver could use.

**Comment by tech189** [comment]
@sitiom you can now install it btw!
