### ISSUE TITLE
composer1 breaks composer

### ISSUE THREAD

**Issue by zd-dalibor** [ScoopInstaller/Versions#286]
if you install composer and composer1 together `scoop install composer1 composer` composer 2 becomes inaccessible and composer and composer1 commands do not work:
![image](https://user-images.githubusercontent.com/226822/116005947-86b72c80-a609-11eb-9560-ff7bccbf4656.png)

**Comment by niheaven** [comment]
Use `scoop reset composer` if you want to use composer 2, `scoop reset composer1` vice versa.
