### ISSUE TITLE
7zip-zstd doesn't register right-click shortcut in file explorer

### ISSUE THREAD

**Issue by sainnhe** [ScoopInstaller/Versions#289]
If you install the `7zip` package it will register a shortcut in file explorer, but the `7zip-zstd` package doesn't.

IMO this is because the `7zip` package uses msi installer while the `7zip-zstd` package uses 7z archive.

The release page of [7zip-zstd](https://github.com/mcmilk/7-Zip-zstd/releases) provides a *.exe, this installer will create a shortcut for 7zip-zstd, maybe we should use this executable instead.

By using this *.exe installer, we can also remove the `7zip` dependency of `7zip-zstd`, current `7zip-zstd` depends on `7zip` which I think is unreasonable.

**Comment by niheaven** [comment]
Scoop won't modify your system except shortcut, so it won't create content menu items. If you install `7-zip` using Scoop, you don't have content menu, right?

**Comment by sainnhe** [comment]
Am I missing something? If I install 7zip, I'll have a right-click shortcut in explorer, but when I uninstall it, the shortcut disappears.

---

Even if it doesn't create a shortcut, I still suggest using the executable, because by this way you don't need to install 7zip as dependency.

**Comment by HUMORCE** [comment]
**context menu**
1. open `apps\7zip-zstd\7zFM.exe`,
2. menubar -> tools -> options -> (tab)7-zip zs -> integrate 7-zip zs to shell context menu and select you want in this panel.

if you already have seted context menu for 7zip(`apps\7zip\7zFM.exe`), it is recommended that unset it in the same place.

**dependency**
the installer is not packed as wix or inno. 7zip is still need as a dependency, scoop cannot decompress `7zip-zstd.exe` installer without it.

**Comment by sainnhe** [comment]
@HUMORCE Thanks!
