### ISSUE TITLE
tomcat7@7.0.109: download via aria2 failed

### ISSUE THREAD

**Issue by Winble** [ScoopInstaller/Versions#294]
ERROR Download failed! (Error 3) Resource was not found
ERROR https://www.apache.org/dist/tomcat/tomcat-7/v7.0.109/bin/apache-tomcat-7.0.109-windows-x64.zip
    referer=https://www.apache.org/dist/tomcat/tomcat-7/v7.0.109/bin/
    dir=D:\Users\Winble\scoop\cache
    out=tomcat7#7.0.109#https_www.apache.org_dist_tomcat_tomcat-7_v7.0.109_bin_apache-tomcat-7.0.109-windows-x64.zip

ERROR & 'D:\Users\Winble\scoop\apps\aria2\current\aria2c.exe' --input-file='D:\Users\Winble\scoop\cache\tomcat7.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.1 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=10144 --continue --summary-interval 0

**Comment by se35710** [comment]
Available at https://archive.apache.org/dist/tomcat/tomcat-7/

**Comment by HUMORCE** [comment]
duplicate https://github.com/ScoopInstaller/Versions/issues/290
