### ISSUE TITLE
POLL: Should we add dots(.) in the package names?

### ISSUE THREAD

**Issue by issaclin32** [ScoopInstaller/Versions#341]
It is somewhat confusing to see packages like
`go114` -> version 1.14? 1.1.4? 11.4?
`cuda110` -> version 11.0? 1.10?
`haskell863` -> version 8.6.3? 8.63?

It would be a lot more clear if we add dots(`.`), such as
`cuda10` -> latest version of CUDA 10 (which is 10.2)
`cuda10.0` -> CUDA 10.0

Waiting for opinions from @ScoopInstaller/maintainers.

[![](https://api.gh-polls.com/poll/01FPF385A0CKR6TFH9GDZV14XK/Apply%20to%20all%20existing%20packages)](https://api.gh-polls.com/poll/01FPF385A0CKR6TFH9GDZV14XK/Apply%20to%20all%20existing%20packages/vote)
[![](https://api.gh-polls.com/poll/01FPF385A0CKR6TFH9GDZV14XK/No.%20Leave%20it%20as%20it%20is.)](https://api.gh-polls.com/poll/01FPF385A0CKR6TFH9GDZV14XK/No.%20Leave%20it%20as%20it%20is./vote)
[![](https://api.gh-polls.com/poll/01FPF385A0CKR6TFH9GDZV14XK/Only%20apply%20to%20newly%20added%20packages)](https://api.gh-polls.com/poll/01FPF385A0CKR6TFH9GDZV14XK/Only%20apply%20to%20newly%20added%20packages/vote)

**Comment by issaclin32** [comment]
/polls 'Apply to all existing packages 'No. Leave it as it is.' "Only apply to newly added packages"

**Comment by rashil2000** [comment]
Dots are clearly better in the long run. But we run into the same problem we face in many other places - manifest migration. How to do it in a way that doesn't inconvenience users?

**Comment by niheaven** [comment]
No idea, but python39 is really convenient 😄

**Comment by issaclin32** [comment]
> How to do it in a way that doesn't inconvenience users?

We can probably implement **package redirections** before doing this change.
This can also apply to package rename/deprecates, and provide better search functions requested in https://github.com/ScoopInstaller/Scoop/issues/4541

For example, creating a new folder `redirected` under *bucket directory*, which contains some manifests like:

**versions/cuda80.json**
```
{
    "redirect": {
        "reason": "renamed",
        "package": "versions/cuda8.0"
    }
}
```

**main/gpg.json**
```
{
    "redirect": {
        "reason": "renamed",
        "package": "main/gnupg"
    }
}
```

**extras/bpgconv.json**
```
{
    "redirect": {
        "reason": "deprecated"
    }
}
```

And **explicitly** prompts user if `renamed` or `alias` is the case. (we can add an option to turn this off)
For example:
```
Package cuda80 has been renamed to cuda8.0. This will rename the folder of your existing installations.
Do you wish to continue [Y/N]?
```


** If there is a better way to do this, please tell me.**

**Comment by rashil2000** [comment]
The UX sounds neat, but I have no idea how (and more importantly, where) these prompts would happen. In libexec/scoop-update.ps1? We will have to do some heavy tracking as to whether a bucket contains a 'redirect' folder, and then cross check which apps from there user has installed.

**Comment by issaclin32** [comment]
I think the issue is somewhat settled, but we need a smart way to implement the alias mechanism.

I will add new packages using the new naming format (`cuda11.0`).
