### ISSUE TITLE
Okular's shortcut in the start menu is not capitalised 

### ISSUE THREAD

**Issue by he3als** [ScoopInstaller/Versions#409]
## Bug Report

**Package Name:** `okular` and potentially `okular-nightly` (not tested nightly)

### Current Behaviour

In the start menu, the shortcut for Okular is not capitalised.

![image](https://user-images.githubusercontent.com/65787561/152214482-d31d89c2-e6a1-4410-97db-6e27fbeb1af1.png)

### Expected Behaviour

It should be capitalised: Okular.

### Additional context/output

Sorry for reporting such a small and quite petty issue but it is kinda annoying me... I can rename it though, but it being capitalised by default would be nice.

### System details

**Windows version:** 10 21H2

**OS architecture:** 64-bit

**PowerShell version:** Powershell 5, build 19041 and revision 1237

**Scoop Configuration:** Default

**Comment by rashil2000** [comment]
Can you send a PR?

**Comment by he3als** [comment]
sorry for not doing a pr earlier, i am not too familiar with scoop but it was quite easy to fix

**Comment by rashil2000** [comment]
No worries :)

**Comment by tech189** [comment]
> potentially okular-nightly (not tested nightly)

Okular nightly's shortcut is already capitalised, thanks for the PR for Okular!
