### ISSUE TITLE
Is there anyway to download specific vim nightly version?

### ISSUE THREAD

**Issue by hungpham3112** [ScoopInstaller/Versions#412]
I'm using python3.10 with `scoop install python.`

But `scoop install vim` just installs the version 8.2.2824 support for python3.6.

Thanks in advance.

**Comment by hungpham3112** [comment]
so after add this bucket, I can use scoop install vim@8.2.4286 right?

**Comment by rashil2000** [comment]
scoop install vim-nightly@8.2.4286
