### ISSUE TITLE
[Request] Add more Gradle versions other than `gradle4`?

### ISSUE THREAD

**Issue by ShadowCreator250** [ScoopInstaller/Versions#417]
I've noticed that `gradle4` exists, but not the other major versions. Is there a reason why only `gradle4` exists? Would it make sense to add the other versions >4 too?

### Information

**Name:** `gradle5` & `gradle6`

**Description:** An open-source build automation tool focused on flexibility and performance. (copied from `main/gradle`)

**Homepage:** https://gradle.org

**Download link(s):** https://services.gradle.org/distributions/gradle-5.6.4-all.zip & https://services.gradle.org/distributions/gradle-6.9.2-all.zip

**Some indication of popularity/repute:** 13k stars on GitHub

**Comment by rashil2000** [comment]
Please make a PR!
