### ISSUE TITLE
windowsdesktop-runtime-lts cannot be searched or installed

### ISSUE THREAD

**Issue by laerhu** [ScoopInstaller/Versions#423]
## Bug Report

**Package Name:** windowsdesktop-runtime-lts

### Current Behaviour

```pwsh
❯ scoop bucket list
extras
main
nerd-fonts
nonportable
versions
❯ scoop search windowsdesktop-runtime
'extras' bucket:
    windowsdesktop-runtime (5.0.14)
❯ scoop install versions/windowsdesktop-runtime-lts
`Couldn't find manifest for 'windowsdesktop-runtime-lts' from 'versions' bucket.`
```
### Expected Behaviour

Intall .net runtime v6.0
### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 7.2.1

**Additional software:** windows-terminal

#### Scoop Configuration

```json
{
  "lastupdate": "2022-02-16T14:49:33.1620284+08:00",
  "aria2-split": 32,
  "aria2-max-connection-per-server": 16,
  "aria2-min-split-size": "1M",
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master",
  "aria2-warning-enabled": false,
  "MSIEXTRACT_USE_LESSMSI": true
}

```

**Comment by rashil2000** [comment]
I can't reproduce this. Scoop is able to find the manifest here.

**Comment by laerhu** [comment]
> I can't reproduce this. Scoop is able to find the manifest here.

Managed to fix this after rm and add the bucket versions.
Thanks for your quick reply.
