### ISSUE TITLE
neovim-nightly@0.7.0-dev-1115-g5cb45dffb: hash check failed

### ISSUE THREAD

**Issue by K1DV5** [ScoopInstaller/Versions#426]
App:         versions/neovim-nightly
URL:         https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    d3fdea40525b8f64bb1c0fc066f4fc148f15b765d56566c2a3bb7f90ef5b768a
Actual:      6134d639fb8c0ad9affb9ab24debc705c942ac78ed50dbd1136cd5fdd465ebfa

**Comment by Sewdohe** [comment]
I am having this issue as well as of 2.21.2022 at 12:41am eastern time
```
Expected:    6134d639fb8c0ad9affb9ab24debc705c942ac78ed50dbd1136cd5fdd465ebfa
Actual:      4491409bf2319b894b61f280a57b8b7967bc55961e0409145fc919c5f3cacc2d
```

**Comment by rashil2000** [comment]
Can you manually download the file and verify hash?

**Comment by Sewdohe** [comment]
> Can you manually download the file and verify hash?
```
PS C:\Users\ifEls\Downloads> Get-FileHash '.\nvim-win64(1).zip'

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          4491409BF2319B894B61F280A57B8B7967BC55961E0409145FC919C5F3CACC2D
```

**Comment by rashil2000** [comment]
Can you create a new issue (with the same title format as this one)?
