### ISSUE TITLE
vim-nightly to persist vimrc and vimfiles

### ISSUE THREAD

**Issue by ShuguangSun** [ScoopInstaller/Versions#435]
## Bug Report

**Package Name:** vim-nightly

### Current Behaviour

not persisit vimrc and vimfiles.

### Expected Behaviour

To persisit vimrc and vimfiles as before.

**Comment by rashil2000** [comment]
This was deliberately removed because persistence causes problems, as opposed to the usual behavior. 

vimrc and vimfiles should be present in their default locations (which is HOME).
