### ISSUE TITLE
ffmpeg-nightly@105871: Download failed

### ISSUE THREAD

**Issue by arinoki** [ScoopInstaller/Versions#438]
The remote server returned an error: (404) Not Found.

**Comment by tech189** [comment]
Not sure why this build was pulled but the latest version installs fine now. Probably same reason for hash failure in #437

**Comment by rashil2000** [comment]
Yeah. Thanks for the heads up @tech189 :)

**Comment by arinoki** [comment]
rn all fine, yes.
