### ISSUE TITLE
Remove apache24 & mysql57?

### ISSUE THREAD

**Issue by rasa** [scoopinstaller/versions#44]
This duplicates https://github.com/lukesampson/scoop/blob/master/bucket/apache.json . I think we should be consistent and only have *different* versions here. Agreed?

**Comment by rasa** [comment]
https://github.com/lukesampson/scoop/blob/master/bucket/mysql.json dups https://github.com/scoopinstaller/versions/blob/master/mysql57.json, too. Why maintain in both places?

**Comment by rasa** [comment]
https://github.com/scoopinstaller/versions/blob/master/mysql57.json is missing `persist`

**Comment by lukesampson** [comment]
Do you think it's useful to have a dupe here for users to lock in the current version? I.e. to make sure an app doesn't get automatically updated to a new major/minor version release when they run `scoop update *`.

Since `apache24` and `mysql57` have autoupdate enabled, the manifests might be auto-updated beyond 2.4/5.7 unless we add something to autoupdate to restrict the major/minor version. Potential new feature allowing this to be more easily and reliably maintained?

**Comment by rasa** [comment]
I think pinning to a specific version should be a separate command (say `scoop pin/unpin apache`), not duplicating files, as they will get out of date,, e.g., https://github.com/scoopinstaller/versions/issues/44#issuecomment-314939807

**Comment by rasa** [comment]
Since we can now install a specific version of an app, via `scoop install app@x.y` let's remove these duplicate manifests. See https://github.com/lukesampson/scoop/issues/1780#issuecomment-338622176 . In fact, why maintain this repo any longer?

**Comment by rasa** [comment]
The hashes are wrong in apache24:

````
                 "https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe"
             ],
             "hash": [
-                "53FFEFD8F0A7E1B41ADD79FBE42D44A5CE665038FE41CB01642AFF26C739D2F4",
+                "6927bc1ac97235877c09137a72348e6a8a11d0b606698a87a7c6092c580309af",
                 "5eea714e1f22f1875c1cb7b1738b0c0b1f02aec5ecb95f0fdb1c5171c6cd93a3"
             ]
         },
@@ -19,7 +19,7 @@
                 "https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x86.exe"
             ],
             "hash": [
-                "1E3A765858F2AEF78EA7C1CD844658E360AFF47C9008009EA2F0A662A43AC05E",
+                "6b0d63c1106a772d429be5a1349b541addc2926d4c9824d3d787b4971c44a579",
                 "fdd1e1f0dcae2d0aa0720895eff33b927d13076e64464bb7c7e5843b7667cd14"
````
Instead of fixing, can we just remove this package?
