### ISSUE TITLE
rclone-beta@1.58.0-beta.6032.807f1ceda: Download failed

### ISSUE THREAD

**Issue by arinoki** [ScoopInstaller/Versions#452]
Exception calling "Read" with "3" argument(s): "The response ended prematurely, with at least 14550733 additional bytes expected."

**Comment by tech189** [comment]
Hmm works for me with both the standard download and `aria2`. Have you tried `scoop cache rm rclone-beta` and installing again?

**Comment by arinoki** [comment]
Yeah, after removing cache new download was fine. So seems rare problem. Will do it first if will happen again and not opening an issue :) 
Thanks :)

**Comment by tech189** [comment]
No problem, good to hear it's all fine!
