### ISSUE TITLE
everything-alpha, add persistance

### ISSUE THREAD

**Issue by tordenflesk** [ScoopInstaller/Versions#485]
## Bug Report

**Package Name:** everything-alpha

### Current Behaviour

Everything-1.5a.ini, Everything-1.5a.db etc. doesn't persist after upgrade

### Expected Behaviour

Everything-1.5a.ini, Everything-1.5a.db etc. should persist after upgrade

### System details

**Windows version:** [e.g. 7, 8, 10]

**OS architecture:** [e.g. 32bit, 64bit]

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by wordpure** [comment]
The files that needs to be retained can refer to [files_created_by_everything](https://www.voidtools.com/support/everything/uninstalling_everything/#files_created_by_everything).
