### ISSUE TITLE
vlc-nightly@20220429: decompress error

### ISSUE THREAD

**Issue by isafadi** [ScoopInstaller/Versions#502]
#### Scoop Configuration

```json
//# Your configuration here
```
C:\Users\yaser>scoop install vlc-nightly
WARN  Purging previous failed installation of vlc-nightly.
ERROR 'vlc-nightly' isn't installed correctly.
Removing older version (20220429).
'vlc-nightly' was uninstalled.
Installing 'vlc-nightly' (20220429) [64bit]
Loading vlc-4.0.0-dev-win64-a478e7bc.7z from cache
Checking hash of vlc-4.0.0-dev-win64-a478e7bc.7z ... ok.
Extracting vlc-4.0.0-dev-win64-a478e7bc.7z ... Invoke-ExternalCommand: C:\Users\yaser\scoop\apps\scoop\current\lib\decompress.ps1:44
Line |
  44 |      $Status = Invoke-ExternalCommand $7zPath $ArgList -LogPath $LogPa …
     |                                       ~~~~~~~
     | Cannot validate argument on parameter 'FilePath'. The argument is null or empty. Provide an argument
     | that is not null or empty, and then try the command again.

Failed to extract files from C:\Users\yaser\scoop\apps\vlc-nightly\20220429\vlc-4.0.0-dev-win64-a478e7bc.7z.
Log file:
  ~\scoop\apps\vlc-nightly\20220429\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Versions/issues/new?title=vlc-nightly%4020220429%3a+decompress+error

**Comment by tech189** [comment]
Could you try again? It's working for me:

```
❯ scoop install versions/vlc-nightly
Installing 'vlc-nightly' (20220429) [64bit]
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: f79ffa|OK  |   6.6MiB/s|C:/Users/me/scoop/cache/vlc-nightly#20220429#https_artifacts.videolan.org_vlc_nightly-win64_20220429-0421_vlc-4.0.0-dev-win64-a478e7bc.7z
Download: Status Legend:
Download: (OK):download completed.
Checking hash of vlc-4.0.0-dev-win64-a478e7bc.7z ... ok.
Extracting vlc-4.0.0-dev-win64-a478e7bc.7z ... done.
Running pre-install script...
Linking ~\scoop\apps\vlc-nightly\current => ~\scoop\apps\vlc-nightly\20220429
Creating shim for 'vlc'.
Creating shortcut for VLC media player (vlc.exe)
Persisting portable
'vlc-nightly' (20220429) was installed successfully!
```

**Comment by isafadi** [comment]
Yup working
Thanks

Sent from my iPhone

On 29 Apr 2022, at 1:46 PM, tech189 ***@***.***> wrote:

﻿

Could you try again? It's working for me:

❯ scoop install versions/vlc-nightly
Installing 'vlc-nightly' (20220429) [64bit]
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: f79ffa|OK  |   6.6MiB/s|C:/Users/me/scoop/cache/vlc-nightly#20220429#https_artifacts.videolan.org_vlc_nightly-win64_20220429-0421_vlc-4.0.0-dev-win64-a478e7bc.7z
Download: Status Legend:
Download: (OK):download completed.
Checking hash of vlc-4.0.0-dev-win64-a478e7bc.7z ... ok.
Extracting vlc-4.0.0-dev-win64-a478e7bc.7z ... done.
Running pre-install script...
Linking ~\scoop\apps\vlc-nightly\current => ~\scoop\apps\vlc-nightly\20220429
Creating shim for 'vlc'.
Creating shortcut for VLC media player (vlc.exe)
Persisting portable
'vlc-nightly' (20220429) was installed successfully!

**Comment by tech189** [comment]
Great! Feel free to close this issue :)
