### ISSUE TITLE
chromium-dev-nosync: Repository archived, deprecate or remove?

### ISSUE THREAD

**Issue by tech189** [ScoopInstaller/Versions#514]
The repository that was building nosync binaries of Chromium Dev has been archived and the project was discontinued on 20th February. Should we remove checkver or move the manifest to a deprecated folder or delete it entirely? Or is there an alternative build we can use?

See: https://github.com/RobRich999/Chromium_Clang

**Comment by rashil2000** [comment]
Can remove checkver for now, and then deprecate after few months

**Comment by tech189** [comment]
Sure. And let's leave a note too.

**Comment by tech189** [comment]
@SnoozeThis wait for 3 months

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/Pr6sSjsjWcY) I will wait until Thu, 11 Aug 2022 11:07:32 UTC and then add a comment.

**Comment by SnoozeThis** [comment]
Resolved.
