### ISSUE TITLE
Ferdium-nightly: update URL

### ISSUE THREAD

**Issue by laserbeans741** [ScoopInstaller/Versions#569]
## Bug Report

ferdium-nightly

### Current Behaviour

The Ferdium maintainers changed release artifact naming convention with version 6.0.0-nightly.84

### Expected Behaviour

I expected ferdium-nightly to update, but failed with 404.

### Additional context/output

The release name was changed to fit the format `Ferdium-win-AutoSetup-6.0.0-nightly.84.exe#/dl.7z`

### Possible Solution

I have a fix on my fork [here](https://github.com/laserbeans741/Versions/tree/fix-ferdium-nightly) and am submitting this issue prior to a merge request per the contribution guide.

The gist is to update the url to:
```json
 "url": "https://github.com/ferdium/ferdium-app/releases/download/v6.0.0-nightly.84/Ferdium-win-AutoSetup-6.0.0-nightly.84.exe#/dl.7z"
```
 and change the autoupdate block to
```json
    "autoupdate": {
        "url": "https://github.com/ferdium/ferdium-app/releases/download/v$version/Ferdium-win-AutoSetup-$version.exe#/dl.7z",
        "hash": {
            "url": "$baseurl/latest.yml",
            "regex": "sha512:\\s+$base64"
        }
```

### System details

**Windows version:** 11 [e.g. 7, 8, 10]

**OS architecture:** 64 bit

**PowerShell version:** 5.1.22000.653

#### Scoop Configuration

```json
{
    "lastUpdate":  "2022-07-01T23:21:00.4601940-05:00",
    "SCOOP_REPO":  "https://github.com/ScoopInstaller/Scoop",
    "SCOOP_BRANCH":  "master"
}
```

**Comment by tech189** [comment]
Thanks for the report! Could you update your fix for version `6.0.0-nightly.85` and make a PR?
