### ISSUE TITLE
olive-editor-nightly@63f74691: download via aria2 failed

### ISSUE THREAD

**Issue by naderi** [ScoopInstaller/Versions#583]
ERROR Download failed! (Error 3) Resource was not found
ERROR https://nightly.link/olive-editor/olive/workflows/ci/master/Olive-63f74691-Windows-x86_64.zip.zip
    referer=https://nightly.link/olive-editor/olive/workflows/ci/master/
    dir=D:\apps\scoop\cache
    out=olive-editor-nightly#63f74691#https_nightly.link_olive-editor_olive_workflows_ci_master_Olive-63f74691-Windows-x86_64.zip.zip

**Comment by tech189** [comment]
Sorry about that. The autoupdate URL had a mistake and wasn't updating, should be all fixed now!
