### ISSUE TITLE
postgresql13@13.8: decompress error

### ISSUE THREAD

**Issue by weizhiwen** [ScoopInstaller/Versions#627]
#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by weizhiwen** [comment]
Failed to extract files from D:\Scoop\apps\postgresql13\13.8\postgresql-13.8-1-windows-x64-binaries.zip.
Log file:
  D:\Scoop\apps\postgresql13\13.8\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Versions/issues/new?title=postgresql13%4013.8%3a+decompress+error

**Comment by weizhiwen** [comment]
ERROR: Cannot open output file : 鏂囦欢鍚嶃€佺洰褰曞悕鎴栧嵎鏍囪娉曚笉姝ｇ‘銆?: D:\Scoop\apps\postgresql13\13.8\\pgsql\pgAdmin 4\web\node_modules\@babel\plugin-proposal-optional-chaining\node_modules\@babel\plugin-syntax-optional-chaining\node_modules\@babel\helper-function-name\node_modules\@babel\template\node_modules\@babel\types\package.json
ERROR: Cannot open output file : 鏂囦欢鍚嶃€佺洰褰曞悕鎴栧嵎鏍囪娉曚笉姝ｇ‘銆?: D:\Scoop\apps\postgresql13\13.8\\pgsql\pgAdmin 4\web\node_modules\@babel\plugin-proposal-optional-chaining\node_modules\@babel\plugin-syntax-optional-chaining\node_modules\@babel\helper-function-name\node_modules\@babel\template\node_modules\@babel\types\README.md

**Comment by kreymerman** [comment]
The same error occurred for PostgreSQL 14 too: https://github.com/ScoopInstaller/Main/issues/3816 and was resolved by using 7-Zip version 19 (with `7zip19.00-helper` dependency).

**Comment by rasa** [comment]
> The same error occurred for PostgreSQL 14 too: [ScoopInstaller/Main#3816](https://github.com/ScoopInstaller/Main/issues/3816) and was resolved by using 7-Zip version 19 (with `7zip19.00-helper` dependency).

Closing as this appears to be the solution.
