### ISSUE TITLE
zig-dev autoupdate not working since 0.10.0-dev.3880

### ISSUE THREAD

**Issue by igaryhe** [ScoopInstaller/Versions#644]
## Bug Report

**Package Name:** zig-dev
### Current Behaviour

the github action seems like not updating zig-dev since 0.10.0-dev.3880

### Expected Behaviour

running `bin\checkver.ps1 zig-dev` shows `zig-dev: 0.10.0-dev.3986 (scoop version is 0.10.0-dev.3880) autoupdate available`

### Additional context/output

pr #638 tries to manually update it, however the pr needs review

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 7.2.6

#### Scoop Configuration

```json
{
  "lastupdate": "2022-09-13T15:01:54.5024938+08:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master",
  "aria2-enabled": false
}

```

**Comment by josephst** [comment]
I've run into the same bug - I think it's related to #642. The autoupdate script is running every 4 hours but the command to update nheko fails and causes the script to stop running before all apps are updated.

**Comment by igaryhe** [comment]
close in favor of pr #643
