### ISSUE TITLE
Add support for older versions of LLVM

### ISSUE THREAD

**Issue by devhawk** [scoopinstaller/versions#65]
Scoop's main bucket has the most up-to-date version of LLVM (6.0.0 as of this writing). Can we add older versions of LLVM to this bucket?

**Comment by r15ch13** [comment]
Since the URLs for LLVM don't change on an update, you can run `scoop install llvm@5.0.1` or `scoop install llvm@4.0.1`.

**Comment by rasa** [comment]
@devhawk It’s nor really, but should be.
