### ISSUE TITLE
`olive-editor-nightly` does not install

### ISSUE THREAD

**Issue by rmobis** [ScoopInstaller/Versions#660]
## Bug Report

**Package Name:** `olive-editor-nightly`

### Current Behaviour

Installing through `scoop install olive-editor-nightly` does not work. The following error is presented:

```
PS G:\projects\personal\scoop-versions-bucket> scoop install olive-editor-nightly
Installing 'olive-editor-nightly' (7fea1476) [64bit] from versions bucket
The remote server returned an error: (404) Not Found.
URL https://nightly.link/olive-editor/olive/workflows/ci/master/Olive-7fea1476-Windows-x86_64.zip.zip is not valid
```

### Expected Behaviour

Package should install correctly and be ready to use after running `scoop install olive-editor-nightly`.

### Possible Solution

I've fixed it on https://github.com/ScoopInstaller/Versions/compare/master...rmobis:scoop-versions-bucket:master, just by updating the `url`, setting the `extract_dir` property and removing the workaround for it being a `.zip.zip` file previously. I have a PR drafted and ready to be submitted as soon as you allow it.

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** 5.1.22000.832

**Additional software:** Windows Terminal

#### Scoop Configuration

```json
{
    "lastUpdate":  "2022-09-21T21:03:35.8919215-03:00"
}
```

**Comment by KrisSchneider** [comment]
@rmobis you should try creating a pull request (PR), it seems you have managed to solve this problem yourself.
