### ISSUE TITLE
[Request] HandBrake Snapshot

### ISSUE THREAD

**Issue by xd-mau5** [ScoopInstaller/Versions#702]
### Information

**Name:** [name of new package]
HandBrake Snapshot
**Description:** [clear and concise details of what it is]
HandBrake is an open-source video transcoder available for Linux, Mac, and Windows, licensed under the [GNU General Public License (GPL) Version 2](https://github.com/HandBrake/HandBrake-snapshots/blob/main/LICENSE).
**Homepage:** [a URL/link]
https://handbrake.fr/
**Download link(s):** [URL(s)/link(s)]
https://github.com/HandBrake/HandBrake-snapshots/releases/download/win/HandBrake-20221005-d026bcf17-x86_64-Win_GUI.zip
**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]
https://github.com/HandBrake/HandBrake

**Comment by rasa** [comment]
Is there a page, or API URL, that identifies the latest snapshot?

**Comment by xd-mau5** [comment]
In the releases page there is a frame with the checksums of the newest release
https://github.com/HandBrake/HandBrake-snapshots/releases
![image](https://user-images.githubusercontent.com/73971855/195456755-c587f0c6-007d-479d-986a-d2a6ed4527ee.png)

**Comment by Zliced13** [comment]
Done in #717
