### ISSUE TITLE
[Request] Python 3.9.15

### ISSUE THREAD

**Issue by b4imetu** [ScoopInstaller/Versions#712]
## Package Request
[Python 3.9.15](https://www.python.org/downloads/release/python-3915/)

does not have a Windows installer (.exe file)

it only have  [Python-3.9.15.tgz](https://www.python.org/ftp/python/3.9.15/Python-3.9.15.tgz) and [Python-3.9.15.tar.xz](https://www.python.org/ftp/python/3.9.15/Python-3.9.15.tar.xz) package

### Information

**Name:** [Python 3.9.15](https://www.python.org/downloads/release/python-3915/)

**Description:** [clear and concise details of what it is]

**Homepage:** https://www.python.org/downloads/release/python-3915/

**Download link(s):** [URL(s)/link(s)]

**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]

**Comment by rasa** [comment]
See https://github.com/ScoopInstaller/Versions/pull/714#issuecomment-1282271471
