### ISSUE TITLE
[Request] Godot Mono Beta 4

### ISSUE THREAD

**Issue by tsilenzio** [ScoopInstaller/Versions#748]
### Information
**Name:** Godot Mono Beta 4
 
**Description:** A feature-packed, cross-platform game engine to create 2D and 3D games from a unified interface.
 
**Homepage:** [Homepage](https://godotengine.org/)
 
**Download link(s):** [Links](https://downloads.tuxfamily.org/godotengine/4.0/beta4/mono/)
 
**Some indication of popularity/repute:** 49k stars

**Comment by cedriclevarlet** [comment]
I am unable to install godot-mono-beta.

Typing the install command produces the following error:

> scoop install godot-mono-beta
```bash
Installing 'godot-mono-beta' (4.0-beta4) [64bit] from versions bucket
Loading Godot_v4.0-beta4_win64.exe.zip from cache
Checking hash of Godot_v4.0-beta4_win64.exe.zip ... ok.
Extracting Godot_v4.0-beta4_win64.exe.zip ... done.
Running pre_install script...
Linking ~\scoop\apps\godot-mono-beta\current => ~\scoop\apps\godot-mono-beta\4.0-beta4
Creating shim for 'godot-mono'.
Can't shim 'godot-mono.exe': File doesn't exist.
```

I might be wrong but looking at: https://github.com/ScoopInstaller/Versions/blob/master/bucket/godot-mono-beta.json, the pre_install command seems to wrongly define the pattern on line 17 as it repeats Godot_ twice:

```powershell
"(Get-ChildItem \"$dir\\Godot_*\\Godot_*.exe\" | Rename-Item -NewName \"godot-mono.exe\");",
```

**Comment by niheaven** [comment]
@cedriclevarlet Sorry I've made a mistake, and now fixed it, please `scoop update` and try again.
