### ISSUE TITLE
[Request] AITrack

### ISSUE THREAD

**Issue by giflw** [ScoopInstaller/Versions#756]
### Information

**Name:** AITrack

**Description:** 6DoF Head tracking software

**Homepage:** https://github.com/AIRLegend/aitrack

**Download link(s):** https://github.com/AIRLegend/aitrack/releases/download/v0.7.1-alpha/aitrack-v0.7.1.zip

**Some indication of popularity/repute:** 68 Forks and 601 Stars

**Comment by rasa** [comment]
@giflw I'm not sure if alpha-only software is applicable for this bucket.
