### ISSUE TITLE
Tomcat 7.0.90 is not found, current version is 7.0.91

### ISSUE THREAD

**Issue by zarebski-m** [scoopinstaller/versions#77]

**Comment by rasa** [comment]
For older versions, we should check in
https://archive.apache.org/dist/tomcat/tomcat-7/?C=N;O=D 
not
https://www.apache.org/dist/tomcat/tomcat-7/
It appears

**Comment by r15ch13** [comment]
Updated to version 7.0.93 with https://github.com/scoopinstaller/versions/commit/8ddf69abb999cfa7c78fa3508547c638f0a6b77b
