### ISSUE TITLE
[Bug]: godot-mono-beta@4.0-beta5 fails to install correctly due to file collision

### ISSUE THREAD

**Issue by cedriclevarlet** [ScoopInstaller/Versions#778]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

godot-mono-beta

### Expected/Current Behaviour

The godot beta 5 has introduced a new console executable in [#67434](https://github.com/godotengine/godot/pull/67434).

This will probably also affect the standard godot-beta package.

Scoop's `pre_install` command attempts to match the executable using this pattern:
`"Get-ChildItem \"$dir\\Godot_*.exe\" | Rename-Item -NewName 'godot-mono.exe'",`

Since the new file `Godot_v4.0-beta5_mono_win64_console.exe` also matches this pattern, it fails to copy the files over correctly and the installation returns the following error:
```bash
Running pre_install script...
Rename-Item: Cannot create a file when that file already exists.
```

### Steps to Reproduce

```console
1. In your terminal type: `scoop install godot-mono-beta`
2. Output should be similar to this:

Installing 'godot-mono-beta' (4.0-beta5) [64bit] from versions bucket
Loading Godot_v4.0-beta5_mono_win64.zip from cache
Checking hash of Godot_v4.0-beta5_mono_win64.zip ... ok.
Extracting Godot_v4.0-beta5_mono_win64.zip ... done.
Running pre_install script...
Rename-Item: Cannot create a file when that file already exists.
Linking ~\scoop\apps\godot-mono-beta\current => ~\scoop\apps\godot-mono-beta\4.0-beta5
Creating shim for 'godot-mono'.
Creating shortcut for Godot Engine (Mono) (godot-mono.exe)
'godot-mono-beta' (4.0-beta5) was installed successfully!

3. Go to the installation directory
4. You should now see that the new console executable is now being incorrectly renamed to godot-mono.exe. The created shortcuts to start godot now point to the console executable instead of the godot executable.
```

### Possible Solution

Update the pre_install pattern to correctly match the godot executable instead of the godot console executable.

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'main' bucket:
384a660a0 (HEAD -> master, origin/master, origin/HEAD) oh-my-posh: Update to version 12.14.1

'versions' bucket:
953fe8f1 (HEAD -> master, origin/master, origin/HEAD) r-patched: Update to version 4.2.2-r83356
```

### Scoop Config

```console
last_update         scoop_branch scoop_repo
-----------         ------------ ----------
17/11/2022 12:47:39 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.7
PSEdition                      Core
GitCommitId                    7.2.7
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by niheaven** [comment]
I cannot reach Windows in a few days, so could you please submit a PR or wait until Monday?

**Comment by cedriclevarlet** [comment]
I might have the time this weekend. Otherwise Monday it is 👍

**Comment by Zliced13** [comment]
@cedriclevarlet  Do you need a fixed version right away?
