### ISSUE TITLE
nodejs8@8.15.0: hash check failed

### ISSUE THREAD

**Issue by elo8** [scoopinstaller/versions#85]
Hi.. I encountered this while trying to install nodejs8. 

Installing 'nodejs8' (8.15.0) [64bit]
node-v8.15.0-win-x64.7z (8.7 MB) [==========================================================================> ]  99%
Checking hash of node-v8.15.0-win-x64.7z ... ERROR Hash check failed!
App:         versions/nodejs8
URL:         https://nodejs.org/dist/v8.15.0/node-v8.15.0-win-x64.7z
First bytes: 37 7A BC AF 27 1C 00 04
Expected:    5317b304111f29c274a6c03375f65b9a2229397d0cd0152c79d32c24ede89f8d
Actual:      4f0ea72d765f01fa100ad1c0768c88c8a7181b61661bbdb2fe202dddd96343ac

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/scoopinstaller/versions/issues/new?title=nodejs8%408.15.0%3a+hash+check+failed

**Comment by rasa** [comment]
The hash in the manifest (the “expected” hash above) is correct. Please try again.
5317b304111f29c274a6c03375f65b9a2229397d0cd0152c79d32c24ede89f8d
