### ISSUE TITLE
[Bug]: wezterm-nightly delay more than 10 days

### ISSUE THREAD

**Issue by tamlok** [ScoopInstaller/Versions#893]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

wezterm-nightly

### Expected/Current Behaviour

The nightly version of wezterm is now `nightly-20221220`. Is it delayed a lot?

### Steps to Reproduce

```console
`scoop install wezterm-nightly`
```

### Possible Solution

Update the version of the nightly build.

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
1240f0078 (HEAD -> master, origin/master, origin/HEAD) mpv-git: Update to version 20230101

'versions' bucket:
7815bf9fe (HEAD -> master, origin/master, origin/HEAD) ipfilter-nightly: Update to version 1672502511
```

### Scoop Config

```console
last_update                       scoop_branch scoop_repo
-----------                       ------------ ----------
2023-01-01T09:51:46.7622951+08:00 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22621.963
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.963
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by tamlok** [comment]
@rashil2000 Do you have any idea that why scoop does not fetch the latest nightly build of wezterm? Thanks!

**Comment by rashil2000** [comment]
Since this is a nightly manifest, it always fetches the latest nightly available on GitHub releases. It doesn't tag versions. You can update it when you desire by running `scoop update wezterm-nightly --force`.
