### ISSUE TITLE
[Bug]: Godot manifests' URLs are now incorrect

### ISSUE THREAD

**Issue by jwmcgettigan** [ScoopInstaller/Versions#955]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

godot-beta, godot-mono-beta, godot-alpha

## Expected
The Godot beta packages should include the latest versions: `v4.0-beta13`, `v4.0-beta14`

## Current
The Godot beta packages only include up to version: `v4.0-beta12`

Upon checking the version of the manifests I received the following errors.
![image](https://user-images.githubusercontent.com/1691061/213964600-e810b114-94f4-46f9-bfe4-b18b931a11af.png)
![image](https://user-images.githubusercontent.com/1691061/213964641-c4ae1cee-1c50-46ca-b3a8-e2ed13007e00.png)

## Note
This technically affects `godot-alpha` as well but since the package will no longer have updates it may not be a cause for concern.

### Steps to Reproduce

```console
Upon checking the URL 'https://godotengine.org/news', it appears to now redirect to 'https://godotengine.org/blog' instead. This is presumably the cause of the issue.
```

### Possible Solution

The solution is simple.  Update the URLs from https://godotengine.org/news to https://godotengine.org/blog.
We could also go a step further and use the URL https://godotengine.org/blog/pre-release/ which would filter for entries relevant to the alpha/beta releases.

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
00e8f5bac (HEAD -> master, origin/master, origin/HEAD) dxwnd: Update to version 2.05.92

'java' bucket:
d05663f9 (HEAD -> master, origin/master, origin/HEAD) temurin11-jre: Update to version 11.0.18-10

'main' bucket:
0b730ebe4 (HEAD -> master, origin/master, origin/HEAD) wakatime-cli: Update to version 1.62.1

'nonportable' bucket:
b9ba59d (HEAD -> master, origin/master, origin/HEAD) spotx-np: Update to version 1.7-20230122-85ebc1

'versions' bucket:
ee22c4b9e (HEAD -> master, origin/master, origin/HEAD) zig-dev: Update to version 0.11.0-dev.1414
```

### Scoop Config

```console
last_update                       scoop_branch scoop_repo
-----------                       ------------ ----------
2023-01-22T22:36:35.2631230-05:00 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.19041.2364
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2364
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by Calinou** [comment]
Fixed by https://github.com/ScoopInstaller/Versions/pull/969.
